name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
    
      - name: update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pip install pytest
          pip install semantic_version
          pytest
    
      - name: Test deployment Locally
        run: |
          uvicorn ThroneAPI:app --host 0.0.0.0 --port 8000 --reload &
          sleep 5  # Wait for FastAPI to start

          test_result=$(curl http://localhost:8000/test?username=error) # Perform a request to /test

          kill $!  # Kill the background process

          if [ "$test_result" == "false" ]; then
            echo "Test failed: /test returned false"
            exit 1
          fi
      
      - name: Test Build
        run: |
          docker-compose build
      - name: Test Deployment
        run: |
          docker-compose up -d
          sleep 5

      - name: Test Deployment
        run: |
          test_result=$(curl http://localhost:8000/test?username=error) # Perform a request to /test

          if [ "$test_result" == "false" ]; then
            echo "Test failed: /test returned false"
            exit 1
          fi
      - name: Stop Deployment
        run: |
          docker-compose down