name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version
        id: get_version
        run: $(grep -oP "API_VERSION = '\K[0-9.]+" ThroneAPI.py || echo "0.0.0") > version
          
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          version=$(cat version)
          docker build -t lordlumineer/throne-api:latest -t lordlumineer/throne-api:${version} .
          docker push lordlumineer/throne-api:latest
          docker push lordlumineer/throne-api:${version}
